import type {
  BusinessType,
  Credit,
  Employees,
  FundPurpose,
  IndustryCategory,
  Revenue,
  Strength,
  YearsInBusiness,
} from "@/app/types";

// 김팀장 정책자금 전자책의 승인 사례를 데이터베이스 형태로 분리.
// 입력값과 가장 가까운 사례를 자동으로 찾아 "유사 사례" 카드에 노출한다.

export interface ApprovalCase {
  id: string;
  title: string;
  industryCategory: IndustryCategory;
  industryLabel: string;
  businessType: BusinessType;
  years: YearsInBusiness;
  revenue: Revenue;
  employees: Employees;
  credit: Credit;
  purpose: FundPurpose;
  strengths: Strength[];
  agency: string;
  approved: string;
  note: string;
  lesson: string; // 전자책 한 줄 교훈
}

export const APPROVAL_CASES: ApprovalCase[] = [
  {
    id: "mfg-parts",
    title: "제조업 · 설비투자",
    industryCategory: "제조",
    industryLabel: "자동차부품 제조",
    businessType: "법인사업자",
    years: "3~7년",
    revenue: "5~10억",
    employees: "5~9명",
    credit: "보통",
    purpose: "시설자금",
    strengths: ["제조업", "기술력", "특허"],
    agency: "기술보증기금",
    approved: "승인 1.5억",
    note: "특허·기술력 근거로 기술평가 가점을 받아 시설자금 확보.",
    lesson: "제조업 + 특허 조합이면 기보 기술평가부터 노리는 게 정석이다.",
  },
  {
    id: "mfg-metal",
    title: "금속가공 · 직접대출",
    industryCategory: "제조",
    industryLabel: "금속가공 제조",
    businessType: "법인사업자",
    years: "3~7년",
    revenue: "5~10억",
    employees: "1~4명",
    credit: "우수",
    purpose: "시설자금",
    strengths: ["제조업"],
    agency: "중소벤처기업진흥공단",
    approved: "승인 2억",
    note: "신용 우수·제조업 강점으로 중진공 직접대출 저리 조달.",
    lesson: "신용이 받쳐주는 제조 법인은 중진공 직접대출이 금리에서 가장 유리하다.",
  },
  {
    id: "mfg-food",
    title: "식품제조 · 운전자금",
    industryCategory: "제조",
    industryLabel: "식품 제조",
    businessType: "법인사업자",
    years: "7년 이상",
    revenue: "10~30억",
    employees: "10명 이상",
    credit: "우수",
    purpose: "운전자금",
    strengths: ["제조업", "고용증가", "수출"],
    agency: "신용보증기금",
    approved: "승인 5억",
    note: "매출·고용·수출 실적을 근거로 신보 대규모 운전자금 승인.",
    lesson: "업력·매출이 탄탄하면 신보 운전자금 한도를 크게 끌어올릴 수 있다.",
  },
  {
    id: "retail-goods",
    title: "도소매 · 운전자금",
    industryCategory: "도소매",
    industryLabel: "생활용품 도소매",
    businessType: "개인사업자",
    years: "1~3년",
    revenue: "1~5억",
    employees: "1~4명",
    credit: "보통",
    purpose: "운전자금",
    strengths: [],
    agency: "신용보증기금",
    approved: "승인 7천만 원",
    note: "안정적 매출과 무연체 이력으로 운전자금 보증 승인.",
    lesson: "특별한 강점이 없어도 무연체·성실납세면 신보 운전자금은 충분히 가능하다.",
  },
  {
    id: "retail-online",
    title: "온라인쇼핑몰 · 운전자금",
    industryCategory: "도소매",
    industryLabel: "온라인 쇼핑몰",
    businessType: "개인사업자",
    years: "1~3년",
    revenue: "1~5억",
    employees: "1~4명",
    credit: "보통",
    purpose: "운전자금",
    strengths: ["수출"],
    agency: "신용보증기금",
    approved: "승인 8천만 원",
    note: "온라인 매출 데이터와 수출(직구·역직구) 실적으로 한도 상향.",
    lesson: "온라인 사업은 매출 데이터 자체가 무기다. 정산내역을 꼭 챙겨라.",
  },
  {
    id: "food-korean",
    title: "외식업 · 긴급자금",
    industryCategory: "음식/외식",
    industryLabel: "한식당(개인)",
    businessType: "개인사업자",
    years: "1~3년",
    revenue: "1억 미만",
    employees: "1~4명",
    credit: "낮음",
    purpose: "긴급자금",
    strengths: [],
    agency: "소상공인시장진흥공단",
    approved: "승인 3천만 원",
    note: "저신용이지만 소상공인 대상 상품으로 단계적 접근해 성공.",
    lesson: "저신용 외식업은 무리한 은행 대신 소진공·재단부터 순서대로 접근한다.",
  },
  {
    id: "food-cafe",
    title: "카페 창업 · 창업자금",
    industryCategory: "음식/외식",
    industryLabel: "카페(청년 창업)",
    businessType: "개인사업자",
    years: "1년 미만",
    revenue: "1억 미만",
    employees: "0명",
    credit: "알 수 없음",
    purpose: "창업자금",
    strengths: ["청년대표"],
    agency: "소상공인시장진흥공단",
    approved: "승인 2천만 원",
    note: "청년 창업자 대상 소진공 창업 자금으로 초기 자본 확보.",
    lesson: "업력이 없어도 청년 창업이면 소진공 청년 상품으로 첫 자금을 만들 수 있다.",
  },
  {
    id: "svc-beauty",
    title: "미용실 · 운전자금",
    industryCategory: "서비스",
    industryLabel: "미용실(개인)",
    businessType: "개인사업자",
    years: "3~7년",
    revenue: "1~5억",
    employees: "1~4명",
    credit: "보통",
    purpose: "운전자금",
    strengths: [],
    agency: "신용보증재단",
    approved: "승인 5천만 원",
    note: "지역 신용보증재단 소상공인 보증으로 운전자금 확보.",
    lesson: "동네 소상공인은 관할 지역재단이 가장 현실적인 1순위 창구다.",
  },
  {
    id: "svc-logistics",
    title: "물류·운송 · 시설자금",
    industryCategory: "서비스",
    industryLabel: "물류/운송",
    businessType: "법인사업자",
    years: "3~7년",
    revenue: "10~30억",
    employees: "10명 이상",
    credit: "우수",
    purpose: "시설자금",
    strengths: ["고용증가"],
    agency: "중소벤처기업진흥공단",
    approved: "승인 4억",
    note: "고용 창출 실적과 성장성으로 중진공 시설자금 승인.",
    lesson: "고용을 늘린 성장 기업은 중진공에서 가점을 받는다. 고용 증빙을 챙겨라.",
  },
  {
    id: "it-sw",
    title: "소프트웨어 · 운전자금",
    industryCategory: "IT/지식서비스",
    industryLabel: "소프트웨어 개발",
    businessType: "법인사업자",
    years: "1~3년",
    revenue: "1~5억",
    employees: "5~9명",
    credit: "보통",
    purpose: "운전자금",
    strengths: ["기술력", "벤처"],
    agency: "기술보증기금",
    approved: "승인 1억",
    note: "벤처 확인·기술력 기반으로 기보 기술평가 통과.",
    lesson: "매출이 작아도 IT·기술기업은 기보 기술평가로 매출의 벽을 넘을 수 있다.",
  },
  {
    id: "it-app",
    title: "앱개발 · 시설/R&D",
    industryCategory: "IT/지식서비스",
    industryLabel: "앱·플랫폼 개발",
    businessType: "법인사업자",
    years: "3~7년",
    revenue: "5~10억",
    employees: "10명 이상",
    credit: "우수",
    purpose: "시설자금",
    strengths: ["기술력", "특허", "연구소", "벤처"],
    agency: "기술보증기금",
    approved: "승인 3억",
    note: "부설연구소·특허·벤처 3박자로 기보 최고 등급 평가.",
    lesson: "연구소+특허+벤처를 갖추면 기술평가 등급이 올라 한도가 껑충 뛴다.",
  },
  {
    id: "const-interior",
    title: "인테리어 · 운전자금",
    industryCategory: "건설/기타",
    industryLabel: "인테리어 시공",
    businessType: "법인사업자",
    years: "3~7년",
    revenue: "5~10억",
    employees: "5~9명",
    credit: "보통",
    purpose: "운전자금",
    strengths: [],
    agency: "신용보증기금",
    approved: "승인 1.2억",
    note: "공사 계약·매출 흐름을 근거로 신보 운전자금 보증.",
    lesson: "수주 기반 업종은 계약서와 세금계산서로 매출 지속성을 증명하는 게 핵심이다.",
  },
];
