import type { Customer, CustomerStage } from "@/app/types";

// Mock 고객 데이터.
// 실제 DB 없이 대시보드/고객 상세에서 사용하며, 다음 단계에서 Supabase로 교체 예정.

export const MOCK_CUSTOMERS: Customer[] = [
  {
    id: "hanbit-precision",
    companyName: "(주)한빛정밀",
    industry: "자동차부품 제조",
    businessType: "법인사업자",
    recommendedAgency: "기술보증기금",
    score: 92,
    stage: "서류 요청",
    nextAction: "설비 견적서·특허증 수령 후 기보 상담 예약",
    lastContactedAt: "2026-06-28",
    updatedAt: "2026-06-30",
    upsellOpportunities: ["기업부설연구소 설립", "벤처기업 확인"],
    memo: "노후 설비 교체 및 신규 라인 증설 자금 필요. 특허 2건 보유, 매출 성장세.",
  },
  {
    id: "happy-bunsik",
    companyName: "행복분식",
    industry: "분식 음식점",
    businessType: "개인사업자",
    recommendedAgency: "소상공인시장진흥공단",
    score: 71,
    stage: "신규 DB",
    nextAction: "첫 상담 전화 — 체납·연체 여부 먼저 확인",
    lastContactedAt: "2026-06-29",
    updatedAt: "2026-06-29",
    upsellOpportunities: ["정기 정책자금 점검"],
    memo: "신규 창업, 긴급 운영자금 필요. 대표 신용 낮음. 저신용 상품부터 단계 접근.",
  },
  {
    id: "daon-commerce",
    companyName: "다온커머스",
    industry: "온라인 쇼핑몰",
    businessType: "개인사업자",
    recommendedAgency: "신용보증기금",
    score: 78,
    stage: "1차 상담 완료",
    nextAction: "부가세 과세표준·정산내역 요청",
    lastContactedAt: "2026-06-27",
    updatedAt: "2026-06-28",
    upsellOpportunities: ["법인전환 컨설팅", "수출바우처 · 무역금융"],
    memo: "역직구 매출 발생. 매출 데이터 정리되면 한도 상향 여지 있음.",
  },
  {
    id: "seil-soft",
    companyName: "(주)세일소프트",
    industry: "소프트웨어 개발",
    businessType: "법인사업자",
    recommendedAgency: "기술보증기금",
    score: 85,
    stage: "접수 준비",
    nextAction: "기술평가 자료 최종 점검 후 접수",
    lastContactedAt: "2026-06-30",
    updatedAt: "2026-07-01",
    upsellOpportunities: ["벤처기업 확인", "정부지원사업(R&D·창업) 연계"],
    memo: "벤처 확인 완료. 기술평가 등급 우수 예상. 운전자금 1억 목표.",
  },
  {
    id: "green-food",
    companyName: "(주)그린푸드",
    industry: "식품 제조",
    businessType: "법인사업자",
    recommendedAgency: "신용보증기금",
    score: 88,
    stage: "심사 중",
    nextAction: "신보 심사 결과 대기 — 추가 자료 요청 대비",
    lastContactedAt: "2026-06-25",
    updatedAt: "2026-06-26",
    upsellOpportunities: ["고용지원금 진단", "세액공제 점검 (통합고용·R&D·투자)"],
    memo: "업력 8년, 수출 실적 보유. 대규모 운전자금 5억 신청.",
  },
  {
    id: "mijin-beauty",
    companyName: "미진헤어",
    industry: "미용실",
    businessType: "개인사업자",
    recommendedAgency: "신용보증재단",
    score: 64,
    stage: "재접촉 예정",
    nextAction: "다음 분기 재접촉 — 매출 회복 시 재검토",
    lastContactedAt: "2026-05-20",
    updatedAt: "2026-06-10",
    upsellOpportunities: ["정기 정책자금 점검"],
    memo: "지역재단 소액 보증 안내함. 현재 자금 수요 낮아 재접촉 대기.",
  },
  {
    id: "hankuk-logis",
    companyName: "(주)한국물류",
    industry: "물류·운송",
    businessType: "법인사업자",
    recommendedAgency: "중소벤처기업진흥공단",
    score: 83,
    stage: "계약 검토",
    nextAction: "컨설팅 계약서 검토 회신 대기",
    lastContactedAt: "2026-06-29",
    updatedAt: "2026-06-30",
    upsellOpportunities: ["고용지원금 진단", "법인세 절세 설계"],
    memo: "고용 증가 실적 있음. 중진공 시설자금 4억 목표. 계약 임박.",
  },
  {
    id: "narae-interior",
    companyName: "나래인테리어",
    industry: "인테리어 시공",
    businessType: "법인사업자",
    recommendedAgency: "신용보증기금",
    score: 76,
    stage: "서류 대기",
    nextAction: "공사 계약서·세금계산서 수령 대기",
    lastContactedAt: "2026-06-26",
    updatedAt: "2026-06-27",
    upsellOpportunities: ["법인세 절세 설계"],
    memo: "수주 기반 매출. 계약서로 매출 지속성 증빙 필요. 운전자금 1.2억.",
  },
  {
    id: "cheongnyeon-cafe",
    companyName: "청년카페",
    industry: "카페",
    businessType: "개인사업자",
    recommendedAgency: "소상공인시장진흥공단",
    score: 68,
    stage: "승인",
    nextAction: "실행 후 재접촉 — 고용 발생 시 지원금 안내",
    lastContactedAt: "2026-06-15",
    updatedAt: "2026-06-20",
    upsellOpportunities: ["고용지원금 진단"],
    memo: "청년 창업 자금 2천만 원 승인 완료. 매장 안정화 후 추가 상담 예정.",
  },
  {
    id: "sunjin-metal",
    companyName: "(주)선진금속",
    industry: "금속가공 제조",
    businessType: "법인사업자",
    recommendedAgency: "중소벤처기업진흥공단",
    score: 90,
    stage: "접수 완료",
    nextAction: "접수 완료 — 실사 일정 조율",
    lastContactedAt: "2026-06-30",
    updatedAt: "2026-07-01",
    upsellOpportunities: ["기업부설연구소 설립", "세액공제 점검 (통합고용·R&D·투자)"],
    memo: "신용 우수 제조 법인. 중진공 직접대출 2억 접수 완료.",
  },
];

export function getCustomerById(id: string): Customer | undefined {
  return MOCK_CUSTOMERS.find((c) => c.id === id);
}

// 진행단계 배지 색상 — Tailwind가 클래스를 purge하지 않도록 전체 문자열을 정적으로 둔다.
export const STAGE_BADGE: Record<CustomerStage, string> = {
  "신규 DB": "bg-slate-100 text-slate-700",
  "1차 상담 완료": "bg-blue-100 text-blue-700",
  "계약 검토": "bg-indigo-100 text-indigo-700",
  "서류 요청": "bg-amber-100 text-amber-700",
  "서류 대기": "bg-orange-100 text-orange-700",
  "접수 준비": "bg-violet-100 text-violet-700",
  "접수 완료": "bg-cyan-100 text-cyan-700",
  "심사 중": "bg-sky-100 text-sky-700",
  승인: "bg-green-100 text-green-700",
  보류: "bg-yellow-100 text-yellow-800",
  실패: "bg-red-100 text-red-700",
  "재접촉 예정": "bg-pink-100 text-pink-700",
};
